name: Publish trustee-proxyenv
run-name: Publish build ${{ github.run_number }} of branch ${{ github.ref_name }} by @${{ github.actor }}

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Get Next Version
      id: semver
      uses: ietf-tools/semver-action@v1
      with:
        token: ${{ github.token }}
        patchList: fix, bugfix, perf, refactor, test, tests, chore, ci
        branch: main
        skipInvalidTags: true

    - name: Create Draft Release
      uses: ncipollo/release-action@v1.13.0
      with:
        prerelease: true
        draft: false
        commit: ${{ github.sha }}
        tag: ${{ steps.semver.outputs.nextStrict }}
        name: ${{ steps.semver.outputs.nextStrict }}
        body: '*pending*'
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and publish Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: Dockerfile
        platforms: linux/amd64
        push: true
        build-args: |
          VERSION=${{ steps.semver.outputs.nextStrict }}
        tags: ghcr.io/${{ github.repository }}:${{ steps.semver.outputs.nextStrict }}, ghcr.io/${{ github.repository }}:latest

    - name: Update CHANGELOG
      id: changelog
      uses: requarks/changelog-action@v1
      with:
        token: ${{ github.token }}
        fromTag: ${{ steps.semver.outputs.nextStrict }}
        toTag: ${{ steps.semver.outputs.current }}
        excludeTypes: ''
        writeToFile: false

    - name: Create Release
      uses: ncipollo/release-action@v1.13.0
      with:
        allowUpdates: true
        makeLatest: true
        draft: false
        tag: ${{ steps.semver.outputs.nextStrict }}
        name: ${{ steps.semver.outputs.nextStrict }}
        body: ${{ steps.changelog.outputs.changes }}
        token: ${{ secrets.GITHUB_TOKEN }}
